# Generated by Django 3.2 on 2022-06-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_rooming'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooming',
        ),
    ]
