# Generated by Django 3.2 on 2022-06-28 23:16

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20220628_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
