# Generated by Django 3.2 on 2022-06-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.page'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(),
        ),
    ]
