# Generated by Django 3.2 on 2022-06-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20220630_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comm',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_content',
            new_name='comm',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment_on',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='timestamp',
            new_name='time',
        ),
    ]
