# Generated by Django 3.2 on 2022-07-05 19:05

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20220630_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='files',
        ),
        migrations.AddField(
            model_name='page',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=page.models.user_directory_path),
        ),
    ]
