# Generated by Django 3.2 on 2022-07-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
