# Generated by Django 3.2 on 2022-06-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('assignment', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prof_name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(to='module.Module'),
        ),
        migrations.AddField(
            model_name='grade',
            name='submission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignment.submission'),
            preserve_default=False,
        ),
    ]
