# Generated by Django 3.2 on 2022-06-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major_types',
            field=models.CharField(choices=[('civil_engineering', 'civil_engineering'), ('chemical_engineering', 'chemical_engineering'), ('mechanical_engineering', 'mechanical_engineering'), ('electrical_engineering', 'electrical_engineering'), ('industrial_engineering', 'industrial_engineering')], default='electrical_engineering', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.CharField(choices=[('Zagazig_University', 'Zagazig _University'), ('Cairo_University', 'Cairo_University'), ('Ain_Shams_University', 'Ain_Shams_University')], default='Zagazig_University', max_length=30),
        ),
    ]
