# Generated by Django 3.2 on 2022-07-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='secret_code',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
