# Generated by Django 3.2 on 2022-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('classroom', '0002_auto_20220630_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(to='question.Question'),
        ),
    ]
