# Generated by Django 3.2 on 2022-06-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instgram',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='linkedin',
        ),
    ]
