# Generated by Django 3.2 on 2022-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
