# Generated by Django 3.2 on 2022-06-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20220627_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major_types',
            field=models.CharField(choices=[('civil_engineering', 'civil_engineering'), ('chemical_engineering', 'chemical_engineering'), ('mechanical_engineering', 'mechanical_engineering'), ('electrical_engineering', 'electrical_engineering'), ('industrial_engineering', 'industrial_engineering')], default='electrical_engineering', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='univeristy_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
