# Generated by Django 3.2 on 2022-06-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20220518_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banner',
        ),
    ]
