# Generated by Django 3.2 on 2022-07-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20220627_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='univeristy_name',
            field=models.CharField(choices=[('Zagazig_University', 'Zagazig _University'), ('Cairo_University', 'Cairo_University'), ('Ain_Shams_University', 'Ain_Shams_University')], default='Zagazig_University', max_length=30),
        ),
    ]
