# Generated by Django 3.2 on 2022-06-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
