# Generated by Django 3.2 on 2022-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('Regular_File', 'Regular_File'), ('Programming_File', 'Programming_File')], default='Regular_File', max_length=30),
        ),
        migrations.AddField(
            model_name='assignment',
            name='language_type',
            field=models.CharField(choices=[('None', 'None'), ('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment_type',
            field=models.CharField(choices=[('Regular_File', 'Regular_File'), ('Programming_File', 'Programming_File')], default='Regular_File', max_length=30),
        ),
        migrations.AddField(
            model_name='submission',
            name='language_type',
            field=models.CharField(choices=[('None', 'None'), ('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], default='None', max_length=30),
        ),
    ]
