# Generated by Django 3.2 on 2022-07-05 10:55

import assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20220629_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=assignment.models.student_directory_path),
        ),
    ]
